### ISSUE TITLE
Tests broken on master

### ISSUE THREAD

**Issue by jacquestardie** [mapbox/untiler#24]
Tests fail on Python 3.6 - see [this Travis run](https://travis-ci.org/mapbox/untiler/builds/229187081).

<details>
<summaryFailure</summary>
<pre>
    def test_extract_mbtiles():
        with TestTiler() as tt:
            testpath = tt.path
            testmbtiles = os.path.join(os.path.dirname(__file__), 'fixtures/testtiles.mbtiles')
            runner = CliRunner()
            result = runner.invoke(cli, [
                'streammbtiles', testmbtiles, testpath, '-z', '16', '-x', '-s',
                '{z}-{x}-{y}-mbtiles.tif', '--co', 'compress=lzw'])
            assert result.exit_code == 0
            expected_checksums = [[13858, 8288, 51489, 31223], [17927, 52775, 411, 9217]]
            for o, c in zip(result.output.rstrip().split('\n'), expected_checksums):
                with rio.open(o) as src:
                    checksums = [src.checksum(i) for i in src.indexes]
>                   assert checksums == c
E                   assert [17927, 52775, 411, 9217] == [13858, 8288, 51489, 31223]
E                     At index 0 diff: 17927 != 13858
E                     Use -v to get the full diff
</pre>
</details>

<br />

Noticed this while working on the [autodeploy branch](https://github.com/mapbox/untiler/tree/autodeploy). Initially thought this was failing due to changes I'd made, but I think this is some sort of config/dependency rot that's happening otherwise.

**Comment by sgillies** [comment]
@jacquestardie did rasterio get updated at the same time? I think that's probably where the checksum changes come from.
